---
ID: "e23fd4bc-e1a4-4383-8e91-dc8940fbd2b1"
Parent: "c626493f-1cc3-4986-a701-f28b83d649f7"
Template: "1404a77a-d5fd-46b3-aa4c-200f3d519979"
Path: /sitecore/system/Modules/Layout Service/Rendering Contents Resolvers/Products
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250214T053952Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "cc83e1a8-e9ae-45bf-a20d-6f06f30b8220"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250214T053952Z
